"""remove other from foods

Revision ID: 84174f569dc4
Revises: decc01bdc470
Create Date: 2026-06-08 13:02:37.146816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84174f569dc4'
down_revision: Union[str, Sequence[str], None] = 'decc01bdc470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'other')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('other', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
