"""add other to foods

Revision ID: decc01bdc470
Revises: 3574b166a8fb
Create Date: 2026-06-08 12:56:08.904935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decc01bdc470'
down_revision: Union[str, Sequence[str], None] = '3574b166a8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('other', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'other')
    # ### end Alembic commands ###
